### PR TITLE
GeoMesaIngestProcessor hang fix.

### PR DESCRIPTION
**Pull request by CannonJunior**
GeoMesaIngestProcessors hang if they are RUNNING and can't connect to Accumulo/Zookeepers.  Added Try and error checking in GeoMesaIngestProcessor.scala to address this.

### CODE REVIEW

**Comment by CannonJunior** [comment]
Commented out the "ruok" functionality.  Produces and error when testing in Nifi, also my not be syntactically correct with more than one Zookeeper.

**Comment by jahhulbert-ccri** [comment]
gonna look soon. feel free to email me next time if you put a PR up so i know!

**Comment by jahhulbert-ccri** [comment]
@CannonJunior do you mind doing a merge squash into a single commit?

**Comment by CannonJunior** [comment]
i did testing on a template with more than just one geomesaingestprocessor and my fix doesn't completely solve things.  Still hangs (sometimes fatally) trying to stop a processor that's looking for non-existant zookeepers.
i'll try to fix, merge, and send you an email.

**Comment by CannonJunior** [comment]
Closing this one, the multiple requests (with few changes) confuses at least me.  Reopening with a fix that tests (manually) well.

**Pull request closed without merging**
